### PR TITLE
Changed cockpit color, improved textures

### PR DESCRIPTION
**Pull request by flyingfisch**
Title says it all.

### CODE REVIEW

**Comment by Pakistan-1** [comment]
Are there any plans to redo the entire cockpit model?

**Comment by flyingfisch** [comment]
Possibly, but between life and work I don't know when that would be. For now the colors are dark gray instead of white, which makes it easier on the eyes.

**Comment by Pakistan-1** [comment]
They look great and Good Luck with Life :)

**Comment by flyingfisch** [comment]
Hey just curious, did you guys know your livery dialog is broken?

**Comment by Pakistan-1** [comment]
Do you know how to fix this ?

**Comment by FGDATA** [comment]
if not I can look at the livery dialog myself :D 
IH-COL.

Thanks Mark..

**Comment by Pakistan-1** [comment]
Israel I merged Marks changes into the master branch :p

**Comment by FGDATA** [comment]
I saw that Suleman
Thanks for taking care of these.
It's great to be a group of collaborators dealing with the progress on the
FGMEMBERs planes.

Israel

**Comment by Pakistan-1** [comment]
I'm happy to help :)

**Comment by flyingfisch** [comment]
FGDATA: no problem, I looked into the livery dialog problem but couldn't see what was wrong. I do know that `liveries.nas` is being included and run, so the dialog should be working. But instead, it is throwing an error, which is weird.

**Pull request merged**
